services:
  productservice:
    build: product-service
  web:
    build: nginx
    ports:
      - "88:88"
  database:
    build: backoffice-db
    ports:
        - "3306:3036"
    environment:
        MYSQL_ROOT_PASSWORD: RootPassword
        MYSQL_DATABASE: Backoffice
        MYSQL_USER: MainUser
        MYSQL_PASSWORD: MainPassword
    
    volumes:
      - db-volume:/var/lib/mysql

volumes:
    db-volume:

