services:
  productservice:
    build: product-service
    depends_on:
      - mysql
  web:
    build: nginx
    ports:
      - "88:88"
    depends_on:
      - productservice

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"

