CREATE DATABASE IF NOT EXISTS nerd;

USE nerd;

CREATE TABLE IF NOT EXISTS characters (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (128) NOT NULL,
    anime VARCHAR (128) NOT NULL
)  ENGINE=INNODB;
